services:
  - type: web
    name: gyani-ai-backend
    env: python
    plan: free  # You can change to 'starter' later if needed
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: LLAMA_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: QWEEN_CODER_API_KEY
        sync: false
      - key: QWEEN_72B_API_KEY
        sync: false
      - key: QWEEN_VL_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: meta-llama/llama-3.1-405b-instruct
      - key: DEBUG
        value: false